# Generated by Django 6.1.1 on 2026-10-06 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Department Title')),
                ('head_name', models.CharField(max_length=200, verbose_name='Department Head')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Faculty Name')),
                ('description', models.TextField(verbose_name='Faculty Description')),
                ('general_info', models.TextField(verbose_name='General Info')),
                ('contact_info', models.TextField(verbose_name='Contact Info')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Program Code')),
                ('title', models.CharField(max_length=200, verbose_name='Program Title')),
                ('description', models.TextField(verbose_name='Program Description')),
                ('coordinator_name', models.CharField(verbose_name='Department Coordinator Name')),
                ('coordinator_contact', models.EmailField(max_length=254, verbose_name='Department Coordinator Contact')),
                ('disciplines', models.TextField(verbose_name='Disciplines list')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='faculty.department', verbose_name='Department Graduate')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Teacher Name')),
                ('position', models.CharField(max_length=200, verbose_name='Teacher Position')),
                ('degree', models.CharField(max_length=200, verbose_name='Teacher Degree')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='faculty.department', verbose_name='Department Graduate')),
            ],
        ),
    ]
