# Generated by Django 6.1.1 on 2026-10-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=200, verbose_name='University with country')),
                ('languages', models.CharField(max_length=200, verbose_name='Study languages')),
                ('seats', models.CharField(max_length=200, verbose_name='Number of Seats')),
                ('deadline', models.DateField(verbose_name='Deadline')),
                ('description', models.TextField(verbose_name='Program Description')),
            ],
        ),
    ]
