# Generated by Django 6.1.1 on 2026-10-06 15:57
import re
from django.db import migrations,models

def split_university_name(apps, schema_editor):
    ExchangeProgram = apps.get_model('faculty', 'ExchangeProgram')
    for program in ExchangeProgram.objects.all():
        raw = program.university.strip()
        split_symbols = re.match(r'^(.*?)\s*\((.*?)\)$', raw)
        if split_symbols:
            program.university_name = split_symbols.group(1).strip()
            program.country = split_symbols.group(2).strip()
        elif ' - ' in raw:
            splited = raw.split(' - ')
            program.university_name = splited[0].strip()
            program.country = splited[1].strip()
        elif ',' in raw:
            splited = raw.split(',',1)
            program.university_name = splited[0].strip()
            program.country = splited[1].strip()
        else:
            program.university_name = raw
            program.country = "не вказано"

        program.save(update_fields = ['university_name', 'country'])

def reverse_split_university_name(apps, schema_editor):

    ExchangeProgram = apps.get_model("faculty", "ExchangeProgram")
    for program in ExchangeProgram.objects.all():
        program.university = f'{program.university_name},({program.country})'
        program.save(update_fields = ['university'])


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_seed_exchange_programs'),
    ]

    operations = [
        migrations.AddField(model_name='exchangeprogram', name='university_name', field=models.CharField(max_length = 255, null = True, verbose_name='University Name'),),

        migrations.AddField(model_name='exchangeprogram', name='country', field=models.CharField(max_length = 255, null = True, verbose_name='Country'),),

        migrations.RunPython(code = split_university_name, reverse_code = reverse_split_university_name),

        migrations.AlterField(model_name='exchangeprogram',name='university',field=models.CharField(default='', max_length=255, verbose_name='University with Country'),),

        migrations.AlterField(model_name= "exchangeprogram", name = "university_name", field = models.CharField(max_length = 255, verbose_name = "University Name"),),

        migrations.AlterField(model_name = "exchangeprogram", name = "country", field = models.CharField(max_length = 255, verbose_name = "Country"),),

        migrations.RemoveField(model_name = "exchangeprogram", name = "university"),
    ]
