# Generated by Django 6.1.1 on 2026-10-06 16:22
import re
from django.db import migrations, models

def convert_seats_to_int(apps,shema_editor):
    ExchangeProgram = apps.get_model('faculty', 'ExchangeProgram')

    for program in ExchangeProgram.objects.all():
        raw = str(program.seats).strip()
        match = re.search(r'(\d+)', raw)
        if match:
            program.seats_int= int(match.group())
        else:
            program.seats_int = 0
        program.save(update_fields=['seats_int'])

def convert_seats_to_str(apps,shema_editor):
    ExchangeProgram = apps.get_model('faculty', 'ExchangeProgram')

    for program in ExchangeProgram.objects.all():
        program.seats_str= str(program.seats)
        program.save(update_fields=['seats_str'])

class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_split_university_and_country'),
    ]

    operations = [
        migrations.AddField(model_name='exchangeprogram',name='seats_int',field=models.PositiveIntegerField(null=True, verbose_name='Number of Seats'),),

        migrations.RunPython(code=convert_seats_to_int,reverse_code=convert_seats_to_str,),

        migrations.AlterField(model_name='exchangeprogram',name='seats_int', field=models.PositiveIntegerField(verbose_name='Number of Seats'),),

        migrations.RemoveField(model_name='exchangeprogram', name='seats',),

        migrations.RenameField(model_name='exchangeprogram', old_name='seats_int', new_name='seats',),
    ]
