# Generated by Django 6.1.1 on 2026-10-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0005_convert_seats_to_int'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeprogram',
            name='country',
            field=models.CharField(max_length=200, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='exchangeprogram',
            name='university_name',
            field=models.CharField(max_length=200, verbose_name='University'),
        ),
    ]
